/** Guião pt-PT — narração do deck tutor (1-indexed). */
export const NARRATION: Record<number, string> = {
  1: 'O ai.tutor começa pelo início de sessão único. O colaborador digita o NIF, recebe um código SMS via Infobip, e entra no ecossistema inteiro com uma só conta. Sem palavra-passe, sem registo duplicado. O Identity Hub da iconsai liga tutor, stats, python, ESG e todas as outras aplicações.',
  2: 'No painel, o aluno vê oito áreas de conhecimento. Cada cartão mostra o progresso do percurso. O destaque roxo é "IA, construir a minha aplicação", onde tudo começa: o aluno vai contar uma história de trabalho e sai com uma app de IA publicada.',
  3: 'Passo um: storytelling por voz. O aluno carrega em gravar, fala naturalmente sobre o que faz no trabalho e que problema quer resolver. A IA transcreve em tempo real com claude sonnet quatro ponto seis e extrai palavras-chave: vendas B2B, industrial, qualificação, leads, automação.',
  4: 'Passo dois: a IA pega na história transcrita e gera um guião estruturado. Define o nome do agente, as ferramentas que vai usar, o fluxo de conversa e os guardrails. Tudo visível para o aluno rever antes de avançar.',
  5: 'Passo três: do guião nasce o system prompt. Mil duzentos e quarenta e sete tokens, modelo claude sonnet quatro ponto seis, temperatura zero vírgula três. O prompt define papel, tom, ferramentas e fluxo em linguagem natural. O aluno pode editar antes de publicar.',
  6: 'Passo quatro: antes de publicar, o aluno testa. A simulação põe o agente dele contra um lead simulado pela IA. Pontuação oito vírgula sete em dez. Controlos ao vivo ajustam temperatura, persona e profundidade técnica. Se aprovar, publica. Se não, refina.',
  7: 'O tool builder mostra o fluxo visual do agente. Cinco blocos no-code: input, CRM lookup, Claude, score Python, output. Cada ligação aparece ao vivo. Deploy ready, caminho da URL já definido.',
  8: 'Modo formação: karaoke word-by-word com TTS da OpenAI. Cada palavra acende ao ritmo da leitura. Três pills de profundidade: simples, técnico e exercício. O aluno escolhe o nível e a IA reescreve.',
  9: 'Exercício com veredicto por Python. O aluno calcula a pontuação do lead: NIF ativo mais dois, oitenta colaboradores mais três, dor clara mais três, orçamento aprovado mais um. Resposta: nove. O grader.py corre os testes e devolve pass, erro zero, doze milissegundos.',
  10: 'Clímax: a aplicação foi publicada. URL real: apps.iconsai.ai barra qualificador-leads-magisatech. Vinte e três conversas, sete leads qualificados, noventa e um por cento de satisfação. Publicada em dois vírgula três segundos, versão um, standalone.',
  11: 'Visão RH da MagisaTech: percurso compliance RGPD com seis colaboradores. Cada um saiu com a sua própria app de IA. Ana Ribeiro, cem por cento, triagem de candidatos. Bruno Castanho, oitenta e cinco por cento, triagem de faturas. Três apps publicadas, média de setenta e nove por cento no percurso.',
  12: 'O ai.tutor transforma cada colaborador num construtor de IA. Conta a história, a IA monta o guião, o prompt, a ferramenta e publica. Não é magia, é tecnologia. Apresentação disponível em iconsai.ai barra tutor.',
}
