/** Script EN -- narration for the tutor deck (1-indexed). */
export const NARRATION: Record<number, string> = {
  1: 'ai.tutor starts with single sign-on. The employee enters their tax ID, receives an SMS code via Infobip, and accesses the entire ecosystem with one account. No passwords, no duplicate registrations. The iconsai Identity Hub connects tutor, stats, python, ESG and all other apps.',
  2: 'On the dashboard, the learner sees eight knowledge areas. Each card shows track progress. The purple highlight is "AI, build my application", where everything begins: the learner will tell a work story and walk away with a published AI app.',
  3: 'Step one: storytelling by voice. The learner presses record, speaks naturally about their work and the problem they want to solve. The AI transcribes in real time with claude sonnet four point six and extracts keywords: B2B sales, industrial, qualification, leads, automation.',
  4: 'Step two: the AI takes the transcribed story and generates a structured script. It defines the agent name, the tools it will use, the conversation flow and the guardrails. Everything visible for the learner to review before moving on.',
  5: 'Step three: the script becomes a system prompt. One thousand two hundred and forty-seven tokens, model claude sonnet four point six, temperature zero point three. The prompt defines role, tone, tools and flow in natural language. The learner can edit before publishing.',
  6: 'Step four: before publishing, the learner tests. The simulation pits their agent against an AI-simulated lead. Score eight point seven out of ten. Live controls adjust temperature, persona and technical depth. Approve to publish, or refine further.',
  7: 'The tool builder shows the agent flow visually. Five no-code blocks: input, CRM lookup, Claude, Python score, output. Each connection appears live. Deploy ready, URL path already defined.',
  8: 'Training mode: word-by-word karaoke with OpenAI TTS. Each word lights up in reading rhythm. Three depth pills: simple, technical and exercise. The learner picks the level and the AI rewrites.',
  9: 'Exercise with Python grading. The learner calculates the lead score: active tax ID plus two, eighty employees plus three, clear pain plus three, approved budget plus one. Answer: nine. The grader.py runs the tests and returns pass, error zero, twelve milliseconds.',
  10: 'Climax: the application is published. Real URL: apps.iconsai.ai slash qualificador-leads-magisatech. Twenty-three conversations, seven qualified leads, ninety-one percent satisfaction. Published in two point three seconds, version one, standalone.',
  11: 'HR view at MagisaTech: LGPD compliance track with six employees. Each one walked away with their own AI app. Ana Ribeiro, one hundred percent, candidate screening. Bruno Castanho, eighty-five percent, tax document triage. Three apps published, average seventy-nine percent on the track.',
  12: 'ai.tutor turns every employee into an AI builder. Tell your story, the AI builds the script, the prompt, the tool and publishes it. It is not magic, it is technology. This presentation is available at iconsai.ai slash tutor.',
}
