/** Guião pt-BR — narração do deck tutor (1-indexed, slide 0 = abertura sem narração). */
export const NARRATION: Record<number, string> = {
  1: 'O ai.tutor começa pelo login único. O colaborador digita o CPF, recebe um código SMS via Infobip, e entra no ecossistema inteiro com uma só conta. Sem senha, sem cadastro duplicado. O Identity Hub da iconsai conecta tutor, stats, python, ESG e todos os outros apps.',
  2: 'No dashboard, o aluno vê oito áreas de conhecimento. Cada card mostra o progresso da trilha. O destaque roxo é "IA, construir minha aplicação", onde tudo começa: o aluno vai contar uma história de trabalho e sair com um app de IA publicado.',
  3: 'Passo um: storytelling por voz. O aluno aperta gravar, fala naturalmente sobre o que faz no trabalho e qual problema quer resolver. A IA transcreve em tempo real com claude sonnet quatro ponto seis e extrai palavras-chave: vendas B2B, industrial, qualificação, leads, automação.',
  4: 'Passo dois: a IA pega a história transcrita e gera um script estruturado. Define o nome do agente, as ferramentas que vai usar, o fluxo de conversa e os guardrails. Tudo visível pro aluno revisar antes de avançar.',
  5: 'Passo três: do script nasce o system prompt. Mil duzentos e quarenta e sete tokens, modelo claude sonnet quatro ponto seis, temperatura zero ponto três. O prompt define papel, tom, ferramentas e fluxo em linguagem natural. O aluno pode editar antes de publicar.',
  6: 'Passo quatro: antes de publicar, o aluno testa. A simulação coloca o agente dele contra um lead simulado pela IA. Score oito ponto sete de dez. Controles ao vivo ajustam temperatura, persona e profundidade técnica. Se aprovar, publica. Se não, refina.',
  7: 'O tool builder mostra o fluxo visual do agente. Cinco blocos no-code: input, CRM lookup, Claude, score Python, output. Cada conexão aparece ao vivo. Deploy ready, caminho da URL já definido.',
  8: 'Modo treinamento: karaokê word-by-word com TTS da OpenAI. Cada palavra acende no ritmo da leitura. Três pills de profundidade: simples, técnico e exercício. O aluno escolhe o nível e a IA reescreve.',
  9: 'Exercício com veredito por Python. O aluno calcula o score do lead: CNPJ ativo mais dois, oitenta funcionários mais três, dor clara mais três, orçamento aprovado mais um. Resposta: nove. O grader.py roda os testes e devolve pass, erro zero, doze milissegundos.',
  10: 'Clímax: a aplicação foi publicada. URL real: apps.iconsai.ai barra qualificador-leads-iconsai. Vinte e três conversas, sete leads qualificados, noventa e um por cento de satisfação. Publicado em dois ponto três segundos, versão um, standalone.',
  11: 'Visão RH da IconsAI: trilha compliance LGPD com seis colaboradores. Cada um saiu com sua própria app de IA. Ana Ribeiro, cem por cento, triagem de candidatos. Bruno Castanho, oitenta e cinco por cento, triagem fiscal. Três apps publicadas, média de setenta e nove por cento na trilha.',
  12: 'O ai.tutor transforma cada colaborador num construtor de IA. Conta a história, a IA monta o script, o prompt, a ferramenta e publica. Não é mágica, é tecnologia. Apresentação disponível em iconsai.ai barra tutor.',
}
